CREATE TABLE IF NOT EXISTS PUBLIC.STUDENT(
	ID VARCHAR(36) not null
		constraint STUDENT_pk
			primary key,
	NAME VARCHAR(50) not null,
	SURNAME VARCHAR(50) not null,
	MAIL VARCHAR(50) not null,
	PHONE_NUMBER VARCHAR(13) not null
);

CREATE TABLE IF NOT EXISTS PUBLIC.STUDENT_DETAIL(

	ID VARCHAR(36) not null
		constraint STUDENT_DETAIL_pk
			primary key,
	STUDENT_ID VARCHAR(36) not null,
	CITY int not null,
	DISTRICT int not null,
	DESC VARCHAR(500) null
);

ALTER TABLE PUBLIC.STUDENT_DETAIL ADD CONSTRAINT IF NOT EXISTS PUBLIC.FK_STUDENT_DETAIL_STUDENT_ID FOREIGN KEY(STUDENT_ID)  REFERENCES PUBLIC.STUDENT (ID);

CREATE TABLE IF NOT EXISTS PUBLIC.FILES(
	ID VARCHAR(36) 	constraint FILES_pk
			primary key,
	STUDENT_ID VARCHAR(36) not null,
	CONTENT_PATH VARCHAR(250)
);

ALTER TABLE PUBLIC.FILES ADD CONSTRAINT IF NOT EXISTS PUBLIC.FK_FILES_STUDENT_ID FOREIGN KEY(STUDENT_ID)  REFERENCES PUBLIC.STUDENT (ID);


CREATE TABLE IF NOT EXISTS PUBLIC.CITY (
	ID int not null
		constraint CITY_pk
			primary key,
NAME varchar(20) NOT NULL,
);

CREATE TABLE IF NOT EXISTS PUBLIC.DISTRICT(

ID int NOT NULL constraint DISTRICT_pk
			primary key,

CITY_ID int NOT NULL,

NAME varchar(25) NOT NULL,

);
