create table STUDENT
(
	ID VARCHAR(36) not null
		constraint STUDENT_pk
			primary key,
	NAME VARCHAR(50) not null,
	SURNAME VARCHAR(50) not null,
	MAIL VARCHAR(50) not null,
	PHONE_NUMBER VARCHAR(13) not null
);

create table STUDENT_DETAIL
(
	ID VARCHAR(36) not null
		constraint STUDENT_DETAIL_pk
			primary key,
	STUDENT_ID VARCHAR(36) not null,
	CITY int not null,
	DISTRICT int not null,
	DESC VARCHAR(500) null
);
ALTER TABLE STUDENT_DETAIL ADD CONSTRAINT FK_STUDENT_DETAIL_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

create table FILES
(
	ID VARCHAR(36),
	STUDENT_ID VARCHAR(36) not null,
	CONTENT_PATH VARCHAR(250)
);
ALTER TABLE FILES ADD CONSTRAINT FK_FILES_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;


CREATE TABLE IF NOT EXISTS CITY (
	ID int not null
		constraint CITY_pk
			primary key,
NAME varchar(20) NOT NULL,
)

CREATE TABLE IF NOT EXISTS DISTRICT(

ID int NOT NULL constraint DISTRICT_pk
			primary key,

CITY_ID int NOT NULL,

NAME varchar(25) NOT NULL,

)